__title__ = 'biology'
__description__ = 'collection of biological classes, methods and functions'
__url__ = ''
__version__ = '0.0.1'
__author__ = 'Foebry'
__author_email__ = 'rain_fabry@hotmail.com'
__license__ = ''
__copyright__ = 'Copyright 2021 Sander Fabry'
